ourjapanlife/findadoc-frontend

.github/CODEOWNERS

Add back CODEOWNERS. This was just a revert, let's edit it as we open source this

add back CODEOWNERS

---

components/CancellationList.vue

Resolved the pagination issue by modifying the function **truncateWebsite** in file **components/CancellationList.vue**
Issue: Returning null for websites which didn't match the regular expression
NA

Resolved the pagination issue

---

components/Alert.vue
components/CancellationList.vue
components/DeleteDialog.vue
components/Testimonial.vue
components/Toolbar.vue
pages/add-clinic.vue

More i18n keys. The en.json file was updated here: https://github.com/ourjapanlife/findadoc-localization/pull/42
To test: Confirm that various languages work on the netlify environment.

add more i18n keys

---

components/CancellationList.vue

I just noticed I missed a few i18n keys... oops

fix a few i18n keys

---

.eslintrc.js
components/Alert.vue
components/AlertsList.vue
components/Toolbar.vue

Until I fix the workflow, need to periodically run prettier to keep things tidy

Prettier write

---

components/ReportedSubmissions.vue
pages/admin/pending.vue

Admin can create fake reports and delete them.

Add Reported Clinics to Admin Dashboard

---

pages/about.vue

This should be reviewed with #125 
This branch was auto-created from the github workflow and addresses the formatting errors introduced in #125.
😄

✨Prettified Code✨

---

.github/workflows/prettier.yml
pages/about.vue

Use a separate branch, since branch protection rules forbid pushes to main

Revisit Prettier workflow

---

components/ActiveClinicData.vue
pages/admin/pending.vue

Moderators can view and update active clinic data, but not delete.

Add active clinics to admin dashboard

---

CONTRIBUTING.md

Feel free to make suggestions or directly edit. Just put some basics to get people directed towards the right things. Let me know your thoughts!

Create Contributing Guidelines

---

nuxt.config.js

Extract CSS into a separate asset.
No tests, config change.
No screenshots for this.

extract css for build

---

components/CancellationList.vue
components/PendingSubmissions.vue
components/Toolbar.vue

Adding more i18n keys to account for recent changes
Dependent on https://github.com/ourjapanlife/findadoc-localization/pull/47 which has been merged, and the submodule updated ✅

more i18n keys

---

LICENSE

Change from 4-clause to 3-clause BSD license for Netlify plan.

change license to 3-clause bsd

---

components/SiteFooter.vue
components/Toolbar.vue
nuxt.config.js

Simplified the footer and toolbar a bit more for mobile. Will need changes to localization. We could set breakpoints to show different toolbar and footer text depending on the device. Most of our users are mobile though.

Update footer and toolbar size and color

---

CODE_OF_CONDUCT.md
LICENSE
components/SiteFooter.vue
components/Toolbar.vue

It's worth considering if we want to move the GitHub link into the Toolbar.
I also tried conditionally rendering the icons  to hide on 'xs', but worked for a bit and then the hamburger menu stopped working, almost as if something very wrong had happened in Vue. :(
I'm not particularly attached to the footer or bar being a certain way, and I quite like the look that @theyokohamalife came up with in #138 
Let me know your thoughts

134  Another idea for smaller footer

---

components/SiteFooter.vue

Links the footer icons with the text so the links are easier to click.

link icon with text

---

components/AlertsList.vue

You picked the wrong day to play, troll
🔥🐉

fraud alert

---

components/AlertsList.vue
components/Disclaimer.vue
pages/index.vue

The code will be refactored later today, but just want to get the information out for now.

create disclaimer component

---

nuxt.config.js

add google verification

---

components/CancellationList.vue
components/PendingSubmissions.vue
data/adminDbTableHeaders.json
pages/add-clinic.vue

Adds true or false value to column if a voucher or ward residency is required.

add voucher col and adjust styles

---

.eslintrc.js
middleware/README.md
pages/login.vue
services/logger.js
utils/logger.js

- Prod logger is using console.log until #164 is done.  
I used several different loggers before and they all have their own complications/advantages. 
For our app, I don't think we need the benefits they provide in exchange for the downsides. [Winston ](https://bundlephobia.com/package/winston@3.3.3)is ~150kb for example as compared to this single file. This is a big perf advantage!
- Site doesn't blow up
- Added first use to the login page. Failing or succeeding login will trigger the logger.

Created centralized logger. 

---

.github/workflows/codeql-analysis.yml

This is a free workflow from GitHub for checking security issues. I thought I would try it on a branch to see if it could help us keep the codebase safe
More info about this tool: https://github.com/github/codeql-action

Try CodeQL Analysis Workflow

---

layouts/default.vue

No issue found. I just noticed a small typo
<sub>This might be my smallest PR ever :grin: </sub>
I am just checking if the app runs normally.

Fix: typo in layouts/default.vue

---

components/CancellationList.vue

Usage of i18n for the voucher status

---

components/ContributorLead.vue
components/Toolbar.vue

Clean up unlinted things so they don't get mixed up in other PRs

post prettier-fix changes

---

components/CancellationList.vue

Adds chips to show if ward residency is required or not.
Check Netlify preview.

add ward residency chips

---

pages/login.vue

Run `yarn dev` and go to http://localhost:3000/login
- Localization is awaiting review:
https://github.com/ourjapanlife/findadoc-localization/pull/71
- Once the localization change is merged, I will point the localization submodule back to the main branch

Make the login page pretty ✨ #58

---

_redirects

Navigating to findadocjp.org should redirect to findadoc.jp

add netlify redirect

---

components/Alert.vue

Emulate on iPhone 12 Pro or 6/7/8 Plus.

Set Alert Cols to Auto

---

components/ActiveClinicData.vue

Adds a kebab menu to the `ActiveClinicData` component of the admin dashboard.
Log into the admin dashboard on pre

add kebabs

---

pages/add-clinic.vue

undo validations

---

data/contributors.json

Add Teresa's Twitter handle to her info card.

add teresa twitter

---

README.md
yarn.lock

bump libraries (including localization)

---

README.md
yarn.lock

Update the README and bump the i18n version.

bump localization

---

components/TwitterTestimonials.vue
netlify.toml
nuxt.config.js
package.json
yarn.lock

This resolves an issue with loading tweets, per #238.
Either:
1. Check the netlify preview, and the widget should load immediately when navigating to the about page
or
1. Pull, add the production twitter key to your env
2. yarn dev
3. test in any browser

Force tweet load on first page refresh

---

assets/variables.scss
components/HeroSection.vue

Add Breakpoint for Hero Column

---

components/Donate.vue
components/HeroSection.vue
content/articles/welcome-to-findadoc.md
pages/index.vue
pages/news/_slug.vue
pages/news/index.vue

Adjust Homepage Margins and Colors

---

package.json

Use localization v1.0.7

---

package.json

Bump i18n libraries to 1.0.9
Open the Netlify preview and try different languages, especially Spanish, Korean, Mongolian

Use latest localization package

---

components/ActiveClinicData.vue
components/CancellationList.vue
components/FeaturedNews.vue
pages/index.vue

fixing vue key error. fixing some other vue keys.

---

package.json

~~Let's see if this prevents the issue Russ was complaining about. Please check the netlify build~~
While this might not fix Russ's issue, I've bumped the i18n versions so we should have better translations

use explicit i18n versions again

---

package.json

Fixed the i18n package publish and bumped to the latest version
This should fix the missing translation issue we were seeing (Maybe not 🙃)

Bump i18n package

---

package.json

Bump i18n library

---

layouts/default.vue
package.json
yarn.lock

Update vaccination appointment alert

add vaccine alert

---

.github/workflows/unit-tests.yml

- Looking at the Actions tab to see the new workflow running the test suite with Jest
New test CI pipeline: https://github.com/ourjapanlife/findadoc-frontend/pull/287/checks?check_run_id=3805352637

Setup jest on CI

---

components/FeaturedNews.vue
pages/index.vue

Merged the News List with Featured news.
